# Generated by Django 5.2.7 on 2025-10-15 21:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SessionApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='room',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Le nom de la salle ne doit contenir que des lettres et des chiffres', regex='^[A-Za-z0-9\\s]+$')]),
        ),
    ]
